<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sistema_emprestimo" nsURI="http://www.example.org/sistemaemprestimo"
    nsPrefix="sistemaemprestimo">
  <eClassifiers xsi:type="ecore:EClass" name="Professor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="departamento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equipamento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoTombamento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisponivel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emprestimo" instanceClassName="sistema_emprestimo.Emprestimo">
    <eTypeParameters/>
    <eTypeParameters/>
    <eTypeParameters/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRetirada" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDevolucaoPrevista"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="equipamentoCodigo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="professorMatricula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equipamentoEmprestado"
        lowerBound="1" eType="#//Equipamento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="professorResponsavel" lowerBound="1"
        eType="#//Professor"/>
  </eClassifiers>
</ecore:EPackage>
