/**
 *
 * $Id$
 */
package sistema_emprestimo.validation;

import java.util.Date;

import sistema_emprestimo.Equipamento;

/**
 * A sample validator interface for {@link sistema_emprestimo.Emprestimo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EmprestimoValidator {
	boolean validate();

	boolean validateDataRetirada(Date value);
	boolean validateDataDevolucaoPrevista(Date value);
	boolean validateEquipamentoEmprestado(Equipamento value);
	boolean validateProfessorResponsavel(Equipamento value);
}
