/**
 *
 * $Id$
 */
package sistema_emprestimo.validation;


/**
 * A sample validator interface for {@link sistema_emprestimo.Equipamento}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EquipamentoValidator {
	boolean validate();

	boolean validateNome(String value);
	boolean validateCodigoTombamento(int value);
	boolean validateIsDisponivel(boolean value);
}
