#

pluginName = My Model Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Professor_type = Professor
_UI_Equipamento_type = Equipamento
_UI_Emprestimo_type = Emprestimo
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Professor_nome_feature = Nome
_UI_Professor_matricula_feature = Matricula
_UI_Professor_departamento_feature = Departamento
_UI_Equipamento_nome_feature = Nome
_UI_Equipamento_codigoTombamento_feature = Codigo Tombamento
_UI_Equipamento_isDisponivel_feature = Is Disponivel
_UI_Emprestimo_dataRetirada_feature = Data Retirada
_UI_Emprestimo_dataDevolucaoPrevista_feature = Data Devolucao Prevista
_UI_Emprestimo_equipamentoEmprestado_feature = Equipamento Emprestado
_UI_Emprestimo_professorResponsavel_feature = Professor Responsavel
_UI_Unknown_feature = Unspecified

